
services:
  fasty-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fasty
    ports:
      - "5432:5432"
    volumes:
      - fasty_data:/var/lib/postgresql/data

  fasty-back:
    build: ./fasty-back
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - fasty-db
    environment:
      DATABASE_HOST: fasty-db
      DATABASE_PORT: 5432
      DATABASE_USER: pabloresk
      DATABASE_PASSWORD: 123
      DATABASE_NAME: fasty

  fasty-front:
    build: ./fasty-front
    ports:
      - "5173:5173"
    depends_on:
      - fasty-back
    environment:
      VITE_API_URL: http://fasty-back:3000

volumes:
  fasty_data:
