services:
  fasty-db:
    build: ./fasty-db
    image: fasty-db-custom
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: fasty-db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 10
    volumes:
      - fasty_data:/var/lib/postgresql/data
      - ./fasty-db/seed:/seed
      

  fasty-back:
    build: ./fasty-back
    restart: always
    ports:
    - "3000:3000"
    depends_on:
      fasty-db:
        condition: service_healthy
    environment:
      DATABASE_HOST: fasty-db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: 123
      DATABASE_NAME: fasty-db

  fasty-front:
    build: ./fasty-front
    ports:
      - "5173:5173"
    depends_on:
      - fasty-back
    environment:
      VITE_API_URL: http://fasty-back:3000


  fasty-seeder:
    image: fasty-db-custom
    depends_on:
    - fasty-db
    - fasty-back
    command: ["/wait/wait-for-it.sh", "fasty-back:3000", "--", "/seed.sh"]
    volumes:
    - ./fasty-db/seed:/seed

volumes:
  fasty_data:


## como es el flujo de los contenedores ? 
# 1. se levanta fasty-db, vacio sin datos
# 2. se levanta fasty-back cuando fasty-db esta listo
# 3. se levanta fasty-seed cuando fasty-back esta listo, lo que hace la siembra de datos
# 4. se levanta fasty-front cuando fasty-back esta listo