services:
  fasty-db:
    build: ./fasty-db
    image: fasty-db-custom
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: fasty-db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 10
    volumes:
      - fasty_data:/var/lib/postgresql/data

  fasty-back:
    build: ./fasty-back
    restart: always
    ports:
    - "3000:3000"
    depends_on:
      fasty-db:
        condition: service_healthy
    environment:
      DATABASE_HOST: fasty-db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: 123
      DATABASE_NAME: fasty-db

  fasty-front:
    build: ./fasty-front
    ports:
      - "5173:5173"
    depends_on:
      - fasty-back
    environment:
      VITE_API_URL: http://fasty-back:3000

volumes:
  fasty_data:


